### PR TITLE
Added Storybook library for components

### PR DESCRIPTION
**Pull request by alecnicolas**
Read more about it [here](https://storybook.js.org/docs/basics/introduction/). Point is, we need it.

### CODE REVIEW

**Comment by ekno27** [comment]
hey what do i do about this

**Comment by alecnicolas** [comment]
> 
> 
> hey what do i do about this

`npm run storybook` 
this will be useful for making components in the future

**Review by ekno27 — CHANGES_REQUESTED** [review]
`~\Desktop\Meso\meso-ui [storybook ≡ +1 ~1 -0 !]> npm run storybook

> meso-ui@0.1.0 storybook C:\Users\Cano\Desktop\Meso\meso-ui
> start-storybook -p 6006

'start-storybook' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meso-ui@0.1.0 storybook: `start-storybook -p 6006`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meso-ui@0.1.0 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Cano\AppData\Roaming\npm-cache\_logs\2020-03-24T01_23_59_749Z-debug.log` 

Error when running,  `storybook` doesnt seem to be in package.json

**Comment by alecnicolas** [comment]
> 
> 
> `~\Desktop\Meso\meso-ui [storybook ≡ +1 ~1 -0 !]> npm run storybook
> 
> > meso-ui@0.1.0 storybook C:\Users\Cano\Desktop\Meso\meso-ui
> > start-storybook -p 6006
> 
> 'start-storybook' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! meso-ui@0.1.0 storybook: `start-storybook -p 6006`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the meso-ui@0.1.0 storybook script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Cano\AppData\Roaming\npm-cache_logs\2020-03-24T01_23_59_749Z-debug.log`
> 
> Error when running, `storybook` doesnt seem to be in package.json

Already messaged you but i'll write it here as well, `cd /storybook`, `npm i` `npm run storybook`

**Review by ekno27 — APPROVED** [review]
cool dude!

**Pull request merged**
